### PR TITLE
responsive styling

### PR DESCRIPTION
**Pull request by FactJacked**
Screen Shot 2021-01-17 at 12 38 09 PM

Screen Shot 2021-01-17 at 12 38 00 PM

Screen Shot 2021-01-17 at 12 37 46 PM

### CODE REVIEW

**Comment by ThePatr10t** [comment]
This is rad! I'll review later when I have some time.

Some caveats
* color coding might change in the future, particularly if I color points based on time. Even if this happens, I like the badges you added
* Im going to make a credits section/page at some point. Please let me know if you'd like me to link to your github.

Thanks again! It might take me a few days to merge. Feeling sick today.

**Comment by FactJacked** [comment]
Hey, glad you liked it. It was a pretty quick effort. I’m in for lots more work on features if you plan on continuing. I know YouTube is being a PITA but at the same time I understand them taking down stuff right now. As far as credit, a mention is fine.

**Comment by FactJacked** [comment]
I think this is now obsolete given what ProPublica has done 😦  But hey, you did it 😄 

https://projects.propublica.org/parler-capitol-videos/

**Comment by ThePatr10t** [comment]
Nice what Propublica did! Looks like they had more bandwidth to play with than I did

**Pull request merged**
